Test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -21,49 +21,49 @@ env:
 
 
 jobs:
-  # lint:
-  #   runs-on: ubuntu-latest
-  #   defaults:
-  #     run:
-  #       shell: bash
-  #   steps:
-  #   # Checkout the repository to the GitHub Actions runner
-  #   - name: Checkout
-  #     uses: actions/checkout@v4
+  lint:
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+    steps:
+    # Checkout the repository to the GitHub Actions runner
+    - name: Checkout
+      uses: actions/checkout@v4
 
-  #   - name: Linting
-  #     run: echo "running linting.."
+    - name: Linting
+      run: echo "running linting.."
   
-  # build:
-  #   needs: [lint]
-  #   runs-on: ubuntu-latest
-  #   defaults:
-  #     run:
-  #       shell: bash
-  #   steps:
-  #   # Checkout the repository to the GitHub Actions runner
-  #   - name: Checkout
-  #     uses: actions/checkout@v4
+  build:
+    needs: [lint]
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+    steps:
+    # Checkout the repository to the GitHub Actions runner
+    - name: Checkout
+      uses: actions/checkout@v4
 
-  #   - name: Build
-  #     run: echo "running build"
+    - name: Build
+      run: echo "running build"
   
-  # publish:
-  #   needs: [build]
-  #   runs-on: ubuntu-latest
-  #   defaults:
-  #     run:
-  #       shell: bash
-  #   steps:
-  #   # Checkout the repository to the GitHub Actions runner
-  #   - name: Checkout
-  #     uses: actions/checkout@v4
+  publish:
+    needs: [build]
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
+    steps:
+    # Checkout the repository to the GitHub Actions runner
+    - name: Checkout
+      uses: actions/checkout@v4
 
-  #   - name: Publish
-  #     run: echo "running publish"
+    - name: Publish
+      run: echo "running publish"
   
   deploy-DEV:
-    #needs: [publish]
+    needs: [publish]
     runs-on: ubuntu-latest
     defaults:
       run:
@@ -78,12 +78,6 @@ jobs:
           ref: feat-1.1.0
           fetch-depth: 10
 
-      # - name: Install yq (mikefarah)
-      #   run: |
-      #     sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
-      #     sudo chmod +x /usr/local/bin/yq
-      #     yq --version
-
       - name: Update image tag in target file
         #working-directory: gitops
         id: update
@@ -91,66 +85,20 @@ jobs:
           set -euo pipefail
           FILE="apps/blog/dev/deploy.yaml"
           IMAGE="850756192530.dkr.ecr.us-east-1.amazonaws.com/devopswithprashant/testing"
-          NEW_TAG=v5.1.0
-          
-
+          NEW_TAG=v3.1.0
           if [ ! -f "$FILE" ]; then
-            echo "ERROR: target file not found: $FILE"
+            echo "ERROR target file not found: $FILE"
             exit 1
           fi
-
           sed -i -E "s|(image:\s*850756192530\.dkr\.ecr\.us-east-1\.amazonaws\.com/devopswithprashant/testing:)[^[:space:]]+|\1${NEW_TAG}|" "$FILE"
-
           # Git config
           git config user.name "${GIT_USER_NAME}"
           git config user.email "${GIT_USER_EMAIL}"
-
           git add "$FILE"
           git commit -m "chore(DEV): bump blog image to ${IMAGE} version ${NEW_TAG}"
           git push origin feat-1.1.0
 
-          # Commit branch name and message (include machine-readable token)
-          #BRANCH="image-update/${APP}-${ENV_NAME}-${GITHUB_RUN_ID}-${GITHUB_SHA::8}"
-          #git checkout -b "$BRANCH"
-          #git add "$FILE"
-          #git commit -m "chore(${ENV_NAME}): bump ${APP} image to ${IMAGE}
-          
-          #gitops-path: ${FILE}
-          #build-url: ${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" || echo "No changes to commit"
-
-          # Push branch
-          #git push origin "$BRANCH"
       
-      # - name: Create PR (optional — uncomment to use PR flow)
-      #   if: false  # set to true to enable PR creation instead of direct push/merge automation
-      #   uses: peter-evans/create-pull-request@v5
-      #   with:
-      #     token: ${{ secrets.GITOPS_TOKEN }}
-      #     branch: ${{ steps.update.outputs.branch || 'image-update' }}
-      #     base: ${{ env.TARGET_BRANCH }}
-      #     title: "image-update: ${APP} -> ${IMAGE} (env: ${ENV_NAME})"
-      #     body: |
-      #       Automated image update
-      #       #gitops-path: ${TARGET_FILE_PATH}
-      #     labels: automated,image-update,gitops-path:${TARGET_FILE_PATH}
-
-      # - name: Merge branch to target (if you want auto-merge)
-      #   if: false  # keep false for non-prod safety; set to true to auto-merge branch into TARGET_BRANCH
-      #   uses: actions-ecosystem/action-pull-request@v1
-      #   with:
-      #     github_token: ${{ secrets.GITOPS_TOKEN }}
-      #     action: merge
-          # additional options available in action; prefer PR + protected-branch rules for prod
-
-#       - name: (Optional) Create commit directly on target branch (force push)
-#         if: false
-#         working-directory: gitops
-#         run: |
-#           # WARNING: direct push to protected branches may be blocked; be careful!
-#           git add "${TARGET_FILE_PATH}"
-#           git commit -m "chore(${ENV_NAME}): bump ${APP} image to ${IMAGE}
-# #gitops-path: ${TARGET_FILE_PATH}" || echo "No changes to commit"
-#           git push origin HEAD:${TARGET_BRANCH}
   
   deploy-QA:
     needs: [deploy-DEV]
@@ -160,11 +108,33 @@ jobs:
         shell: bash
     steps:
     # Checkout the repository to the GitHub Actions runner
-    - name: Checkout
-      uses: actions/checkout@v4
+      - name: Checkout gitops repo
+        uses: actions/checkout@v4
+        with:
+          repository: "devopswithprashant/gitops-test"
+          token: ${{ secrets.GHEC_TOKEN_K8 }}
+          ref: feat-1.1.0
+          fetch-depth: 10
 
-    - name: deploy
-      run: echo "running deploy QA"
+      - name: Update image tag in target file
+        #working-directory: gitops
+        id: update
+        run: |
+          set -euo pipefail
+          FILE="apps/blog/dev/deploy.yaml"
+          IMAGE="850756192530.dkr.ecr.us-east-1.amazonaws.com/devopswithprashant/testing"
+          NEW_TAG=v3.1.0
+          if [ ! -f "$FILE" ]; then
+            echo "ERROR target file not found: $FILE"
+            exit 1
+          fi
+          sed -i -E "s|(image:\s*850756192530\.dkr\.ecr\.us-east-1\.amazonaws\.com/devopswithprashant/testing:)[^[:space:]]+|\1${NEW_TAG}|" "$FILE"
+          # Git config
+          git config user.name "${GIT_USER_NAME}"
+          git config user.email "${GIT_USER_EMAIL}"
+          git add "$FILE"
+          git commit -m "chore(DEV): bump blog image to ${IMAGE} version ${NEW_TAG}"
+          git push origin feat-1.1.0
 
   
 
